from ... import exc as exc

class AsyncMethodRequired(exc.InvalidRequestError): ...
class AsyncContextNotStarted(exc.InvalidRequestError): ...
class AsyncContextAlreadyStarted(exc.InvalidRequestError): ...
