from typing import Any

from . import operators as operators
from .base import HasCacheKey as HasCacheKey
from .traversals import anon_map as anon_map
from .visitors import InternalTraversal as InternalTraversal
from .. import util as util

EMPTY_ANNOTATIONS: Any

class SupportsAnnotations: ...
class SupportsCloneAnnotations(SupportsAnnotations): ...
class SupportsWrappingAnnotations(SupportsAnnotations): ...

class Annotated:
    def __new__(cls, *args: Any): ...
    __dict__: Any = ...
    def __init__(self, element: Any, values: Any) -> None: ...
    def __reduce__(self): ...
    def __hash__(self) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    @property
    def entity_namespace(self): ...

annotated_classes: Any
