from typing import Any
from typing import Callable
from typing import Generic
from typing import Optional
from typing import overload
from typing import Type
from typing import TypeVar

from .. import util as util
from ..orm import attributes as attributes
from ..orm import interfaces as interfaces
from ..sql import ColumnElement
from ..sql import elements as elements

HYBRID_METHOD: Any
HYBRID_PROPERTY: Any
_T = TypeVar("_T")
_T2 = TypeVar("_T2")

class hybrid_method(interfaces.InspectionAttrInfo):
    is_attribute: bool = ...
    extension_type: Any = ...
    func: Any = ...
    def __init__(self, func: Any, expr: Optional[Any] = ...) -> None: ...
    def __get__(self, instance: Any, owner: Any): ...
    expr: Any = ...
    def expression(self, expr: Any) -> hybrid_method: ...

class hybrid_property(interfaces.InspectionAttrInfo, Generic[_T]):
    is_attribute: bool = ...
    extension_type: Any = ...
    # fget: Any = ...
    fget: Callable[[Any], _T] = ...
    # fset: Any = ...
    fset: Callable[[Any, _T], None] = ...
    # fdel: Any = ...
    fdel: Callable[[Any], None] = ...
    # expr: Any = ...
    expr: Callable[[Any], ColumnElement] = ...
    custom_comparator: Any = ...
    update_expr: Any = ...
    def __init__(
        self,
        fget: Callable[[Any], _T],
        fset: Optional[Callable[[Any, _T], None]] = ...,
        fdel: Optional[Callable[[Any], None]] = ...,
        expr: Optional[Callable[[Type[Any]], ColumnElement]] = ...,
        custom_comparator: Optional[Any] = ...,
        update_expr: Optional[Any] = ...,
    ) -> None: ...
    @overload
    def __get__(self, instance: None, owner: Any) -> ColumnElement: ...
    @overload
    def __get__(self, instance: object, owner: Any) -> _T: ...
    def __set__(self, instance: object, value: _T) -> None: ...
    def __delete__(self, instance: object) -> None: ...
    @property
    def overrides(self): ...
    def getter(self, fget: Callable[[], _T2]) -> hybrid_property[_T2]: ...
    def setter(
        self, fset: Callable[[Any, _T2], None]
    ) -> hybrid_property[_T2]: ...
    def deleter(self, fdel: Callable[[Any], None]) -> hybrid_property[_T]: ...
    def expression(
        self, expr: Callable[[Type[Any]], ColumnElement]
    ) -> hybrid_property[_T]: ...
    def comparator(
        self, comparator: Callable[[Any], Any]
    ) -> hybrid_property[_T]: ...
    def update_expression(
        self, meth: Callable[[Any, Any], Any]
    ) -> hybrid_property[_T]: ...

class Comparator(interfaces.PropComparator):
    property: Any = ...
    expression: Any = ...
    def __init__(self, expression: Any) -> None: ...
    def __clause_element__(self): ...
    def adapt_to_entity(self, adapt_to_entity: Any): ...

class ExprComparator(Comparator):
    cls: Any = ...
    expression: Any = ...
    hybrid: Any = ...
    def __init__(self, cls: Any, expression: Any, hybrid: Any) -> None: ...
    def __getattr__(self, key: Any): ...
    @property
    def info(self): ...
    @property
    def property(self): ...
    def operate(self, op: Any, *other: Any, **kwargs: Any): ...
    def reverse_operate(self, op: Any, other: Any, **kwargs: Any): ...
