import sys

if sys.version_info >= (3, 0):
    import asyncio as asyncio  # noqa
    from typing import Any
    from typing import Callable
    from typing import Coroutine
    def await_only(awaitable: Coroutine) -> Any: ...
    def await_fallback(awaitable: Coroutine) -> Any: ...
    async def greenlet_spawn(
        fn: Callable, *args: Any, _require_await: Any = ..., **kwargs: Any
    ) -> Any: ...
    class AsyncAdaptedLock:
        mutex: Any = ...
        def __init__(self) -> None: ...
        def __enter__(self): ...
        def __exit__(self, *arg: Any, **kw: Any) -> None: ...
